version: 2
jobs:
  checkout_and_install_dependencies:
    docker:
      - image: circleci/node:9.4.0-browsers
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  run_unit_test:
    docker:
      - image: circleci/node:9.4.0-browsers
    steps:
      - run: npm run test:ci

  run_e2e_test:
    docker:
      - image: circleci/node:9.4.0-browsers
    steps:
      - run: npm run e2e

workflows:
  version: 2
  build_and_test:
    jobs:
    - checkout_and_install_dependencies
    - run_unit_test:
        requires:
        - checkout_and_install_dependencies
    - run_e2e_test:
        requires:
        - run_unit_test
